### ISSUE TITLE
V2 PCB to-do list

### ISSUE THREAD

**Issue by HWXLR8** [HWXLR8/niubkb#2]
- [x] fix right hand column wiring with `mirror.column_net`
- [x] increase pad size of MX key
- [x] increase pad size of pro micro
- [x] move pro micro silkscreen outline to non silk layer
- [x] increase tilt slightly
- [x] add thumb keys to innermost column and bottom row
