### ISSUE TITLE
V3 PCB to-do list

### ISSUE THREAD

**Issue by HWXLR8** [HWXLR8/niubkb#3]
- [x] Move pinky row down slightly
- [ ] Add MX hotswaps
- [x] Straighten USB cutout corners

**Comment by HWXLR8** [comment]
closing issue, hotswaps no longer in scope for this release.
